<?php
namespace AppBundle\FormHandler;
use Mbx\ArchitectBundle\Abstracts\AbstractFormHandler;
use Mbx\ArchitectBundle\Interfaces\EntityInterface;
use AppBundle\Form\PostType;

/**
 * Generated by MbxArchitectBundle
 */
class PostFormHandler extends AbstractFormHandler
{
    public function initDeleteRouteName()
    {
       return 'post_delete';
    }

    public function initFormTypeNS()
    {
        return PostType::class;
    }
    public function beforeCheckForm(EntityInterface $entity)
    {
        // TODO: Implement beforeCheckForm() method.
    }

    public function afterCheckForm(EntityInterface $entity)
    {
        // TODO: Implement afterCheckForm() method.
    }

    public function beforeCheckDeleteForm(EntityInterface $entity)
    {
        // TODO: Implement beforeCheckDeleteForm() method.
    }

    public function afterCheckDeleteForm(EntityInterface $entity)
    {
        // TODO: Implement afterCheckDeleteForm() method.
    }
}