services:
    appbundle.category_manager:
        class: AppBundle\Manager\CategoryManager
        parent: mbx.abstract_entity_manager
    appbundle.category_form_handler:
        class: AppBundle\FormHandler\CategoryFormHandler
        parent: mbx.abstract_form_handler
        arguments: ['@appbundle.category_manager']
    appbundle.post_manager:
        class: AppBundle\Manager\PostManager
        parent: mbx.abstract_entity_manager
    appbundle.post_form_handler:
        class: AppBundle\FormHandler\PostFormHandler
        parent: mbx.abstract_form_handler
        arguments: ['@appbundle.post_manager']


#    user_admin.example:
#        class: UserAdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
